SELECT 
    MACHINE.NAME AS SYSTEM_NAME,
    SYSTEM_DESCRIPTION,
    MACHINE.IP,
    MACHINE.MAC,
    MACHINE.ID as TOPIC_ID
FROM MACHINE
WHERE 
    -- Calculate days since March 1, 2024
    DATEDIFF(CURDATE(), '2024-03-01') >= (MACHINE.ID % 30) -- 30 day rollout
AND EXISTS (
    SELECT 1 
    FROM CATALOG.SAM_CATALOG 
    JOIN SAM_MACHINE_JT ON CATALOG.SAM_CATALOG.ID = SAM_MACHINE_JT.SAM_CATALOG_ID 
    WHERE MACHINE.ID = SAM_MACHINE_JT.MACHINE_ID 
    AND CATALOG.SAM_CATALOG.NAME LIKE 'Java 8 Update%'
) 