-- Basic Embedded Java Report
-- Lists all machines with their Java installations
SELECT 
    M.NAME as 'Machine Name',
    M.IP as 'IP Address',
    MCI.STR_FIELD_VALUE as 'Java Installations'
FROM MACHINE M
LEFT JOIN MACHINE_CUSTOM_INVENTORY MCI 
    ON MCI.ID = M.ID
WHERE MCI.SOFTWARE_ID = (SELECT ID FROM SOFTWARE WHERE DISPLAY_NAME = 'CI-Java_location')
    AND MCI.STR_FIELD_VALUE != 'NO_JAVA_FOUND'
    AND MCI.STR_FIELD_VALUE != 'LOG_NOT_FOUND'
    AND MCI.STR_FIELD_VALUE != '<br/>'
ORDER BY M.NAME;

-- Parsed Java Installations (Split by Application)
-- Breaks down each Java installation into its components
SELECT 
    M.NAME as 'Machine Name',
    M.IP as 'IP Address',
    SUBSTRING_INDEX(SUBSTRING_INDEX(MCI.STR_FIELD_VALUE, '|', n.n), '|', -1) as Java_Entry,
    SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(MCI.STR_FIELD_VALUE, '|', n.n), '|', -1), ',', 1) as 'Executable',
    SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(MCI.STR_FIELD_VALUE, '|', n.n), '|', -1), ',', 2), ',', -1) as 'Full Path',
    SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(MCI.STR_FIELD_VALUE, '|', n.n), '|', -1), ',', 3), ',', -1) as 'File Version',
    SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(MCI.STR_FIELD_VALUE, '|', n.n), '|', -1), ',', 4), ',', -1) as 'Product Version',
    SUBSTRING_INDEX(SUBSTRING_INDEX(SUBSTRING_INDEX(MCI.STR_FIELD_VALUE, '|', n.n), '|', -1), ',', -1) as 'Vendor'
FROM MACHINE M
LEFT JOIN MACHINE_CUSTOM_INVENTORY MCI 
    ON MCI.ID = M.ID
JOIN (
    SELECT a.N + b.N * 10 + 1 n
    FROM 
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
        (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
    ORDER BY n
) n ON n.n <= LENGTH(MCI.STR_FIELD_VALUE) - LENGTH(REPLACE(MCI.STR_FIELD_VALUE, '|', '')) + 1
WHERE MCI.SOFTWARE_ID = (SELECT ID FROM SOFTWARE WHERE DISPLAY_NAME = 'CI-Java_location')
    AND MCI.STR_FIELD_VALUE != 'NO_JAVA_FOUND'
    AND MCI.STR_FIELD_VALUE != 'LOG_NOT_FOUND'
    AND MCI.STR_FIELD_VALUE != '<br/>'
ORDER BY M.NAME;

-- Summary Report by Java Version
-- Groups installations by version and vendor
SELECT 
    SUBSTRING_INDEX(SUBSTRING_INDEX(Java_Entry, ',', 4), ',', -1) as 'Product Version',
    SUBSTRING_INDEX(Java_Entry, ',', -1) as 'Vendor',
    COUNT(*) as 'Installation Count'
FROM (
    SELECT 
        SUBSTRING_INDEX(SUBSTRING_INDEX(MCI.STR_FIELD_VALUE, '|', n.n), '|', -1) as Java_Entry
    FROM MACHINE M
    LEFT JOIN MACHINE_CUSTOM_INVENTORY MCI 
        ON MCI.ID = M.ID
    JOIN (
        SELECT a.N + b.N * 10 + 1 n
        FROM 
            (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
            (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
        ORDER BY n
    ) n
    WHERE MCI.SOFTWARE_ID = (SELECT ID FROM SOFTWARE WHERE DISPLAY_NAME = 'CI-Java_location')
        AND MCI.STR_FIELD_VALUE != 'NO_JAVA_FOUND'
        AND MCI.STR_FIELD_VALUE != 'LOG_NOT_FOUND'
        AND MCI.STR_FIELD_VALUE != '<br/>'
        AND n.n <= LENGTH(MCI.STR_FIELD_VALUE) - LENGTH(REPLACE(MCI.STR_FIELD_VALUE, '|', '')) + 1
) split_data
GROUP BY 
    SUBSTRING_INDEX(SUBSTRING_INDEX(Java_Entry, ',', 4), ',', -1),
    SUBSTRING_INDEX(Java_Entry, ',', -1)
ORDER BY 'Product Version';
